#!/bin/bash
#$ -N pipeline
#$ -l mem=2G
#$ -cwd
#$ -pe default 2
#$ -o $HOME
#$ -e $HOME
#$ -l h=*cippy*

export PATH="$HOME/miniconda/bin:$PATH"
eval "$(conda shell.bash hook)"
conda activate MLinPractice


echo "loading data"
code/load_data.sh
echo "preprocessing"
code/preprocessing.sh
echo "feature extraction"
code/feature_extraction.sh
echo "classification"
code/classification.sh

conda deactivate
